TEXTS = {
    "fa": {
        "choose_language": "زبان خود را انتخاب کنید 🌐",
        "welcome": "به ربات چالش لایکی خوش اومدی! 🌟\nاینجا مالک‌های کانال چالش می‌سازن و هرکی بیشترین لایک بگیره برنده می‌شه.",
        "main_menu": "یکی از گزینه‌ها رو انتخاب کن:",
        "btn_new_challenge": "➕ ساخت چالش جدید",
        "btn_about": "ℹ️ درباره ربات",
        "btn_creator": "👑 سازنده ربات",
        "ask_channel": "لطفاً اول ربات رو تو کانالت **ادمین کامل** کن، بعد آیدی یا لینک کانالت رو بفرست (مثل @yourchannel):",
        "bot_not_admin": "❌ ربات هنوز تو این کانال ادمین نیست. اول ادمینش کن، بعد دوباره لینک رو بفرست.",
        "ask_winners_count": "چند نفر برنده‌ی نهایی داره چالشت؟ (فقط عدد بفرست، مثلاً 3)",
        "ask_prize": "🏆 جایزه‌ی نفر {rank} رو بنویس:",
        "ask_start_time": "چالش از کی شروع بشه؟ (فرمت: YYYY-MM-DD HH:MM ، مثلاً 2026-09-20 18:00)",
        "ask_end_time": "چالش کی تموم بشه؟ (همون فرمت بالا)",
        "ask_stars": "آیا واکنش ستاره‌ای (⭐️) هم فعال باشه؟",
        "btn_yes": "✅ بله",
        "btn_no": "❌ نه",
        "ask_stars_rate": "هر ⭐️ چند لایک حساب بشه؟ (فقط عدد، مثلاً 2)",
        "preview_ready": "این پیش‌نمایش چالشته 👇",
        "btn_confirm": "✅ تأیید و ارسال",
        "btn_edit": "✏️ لغو و از اول",
        "challenge_published": "✅ چالش با موفقیت تو کانالت پست و پین شد!\nلینک ثبت‌نام مخصوص چالشت:\n{link}",
        "ask_name": "اسمت رو بفرست:",
        "ask_age": "سنت چنده؟",
        "ask_city": "اهل کجایی؟",
        "ask_photo": "یه عکس ازت بفرست تا به بنرت اضافه بشه 📸",
        "registered": "✅ ثبت‌نامت تموم شد! تو شرکت‌کننده‌ی شماره {number} هستی.\nبنرت الان تو کانال پست شد 🎉",
        "must_join_first": "⚠️ اول باید عضو کانال بشی، بعد بتونی لایک کنی.",
        "check_again": "✅ عضو شدم، دوباره چک کن",
        "already_liked": "قبلاً لایک کرده بودی 😊",
        "like_added": "❤️ لایکت ثبت شد!",
        "about_text": "🤖 این ربات چالش‌های لایکی رو برای مالک کانال‌ها مدیریت می‌کنه:\n➕ ساخت چالش با جایزه دلخواه\n❤️ دکمه لایک با جوین اجباری\n⭐️ واکنش ستاره‌ای مستقیم به کانال\n🏆 اعلام خودکار برنده‌ها\nکاملاً رایگانه ❤️",
        "creator_text": "👑 سازنده و طراح ربات:\n〘Cactuc = نــوید〙\n@cactuc580"
    },
    "en": {
        "choose_language": "Choose your language 🌐",
        "welcome": "Welcome to the Like Challenge Bot! 🌟\nChannel owners create challenges here, and whoever gets the most likes wins.",
        "main_menu": "Choose an option:",
        "btn_new_challenge": "➕ Create New Challenge",
        "btn_about": "ℹ️ About the Bot",
        "btn_creator": "👑 Bot Creator",
        "ask_channel": "First make the bot a full admin in your channel, then send your channel username or link (e.g. @yourchannel):",
        "bot_not_admin": "❌ The bot is not an admin there yet. Please add it as admin, then resend the link.",
        "ask_winners_count": "How many final winners does your challenge have? (send a number, e.g. 3)",
        "ask_prize": "🏆 Enter the prize for rank {rank}:",
        "ask_start_time": "When should the challenge start? (format: YYYY-MM-DD HH:MM)",
        "ask_end_time": "When should it end? (same format)",
        "ask_stars": "Enable Star (⭐️) reactions too?",
        "btn_yes": "✅ Yes",
        "btn_no": "❌ No",
        "ask_stars_rate": "How many likes per ⭐️? (number)",
        "preview_ready": "Here is your challenge preview 👇",
        "btn_confirm": "✅ Confirm & Publish",
        "btn_edit": "✏️ Cancel & restart",
        "challenge_published": "✅ Challenge published and pinned!\nYour registration link:\n{link}",
        "ask_name": "Send your name:",
        "ask_age": "Your age?",
        "ask_city": "Your city?",
        "ask_photo": "Send a photo to add to your banner 📸",
        "registered": "✅ Registered! You are participant #{number}.\nYour banner is now posted in the channel 🎉",
        "must_join_first": "⚠️ You must join the channel before liking.",
        "check_again": "✅ I joined, check again",
        "already_liked": "You already liked this 😊",
        "like_added": "❤️ Your like was recorded!",
        "about_text": "🤖 This bot runs like-challenges for channel owners:\n➕ Create a challenge with custom prizes\n❤️ Like button with forced join\n⭐️ Direct star reactions to the channel\n🏆 Automatic winner announcement\nCompletely free ❤️",
        "creator_text": "👑 Bot creator:\n〘Cactuc = نــوید〙\n@cactuc580"
    },
    "ru": {
        "choose_language": "Выберите язык 🌐",
        "welcome": "Добро пожаловать в Like Challenge Bot! 🌟",
        "main_menu": "Выберите вариант:",
        "btn_new_challenge": "➕ Создать челлендж",
        "btn_about": "ℹ️ О боте",
        "btn_creator": "👑 Создатель бота",
        "ask_channel": "Сначала сделайте бота полным админом канала, затем пришлите ссылку/юзернейм канала:",
        "bot_not_admin": "❌ Бот ещё не админ там. Добавьте его, затем пришлите ссылку снова.",
        "ask_winners_count": "Сколько победителей в вашем челлендже? (число)",
        "ask_prize": "🏆 Приз за {rank} место:",
        "ask_start_time": "Когда начнётся челлендж? (формат: YYYY-MM-DD HH:MM)",
        "ask_end_time": "Когда закончится? (тот же формат)",
        "ask_stars": "Включить звёздные реакции (⭐️)?",
        "btn_yes": "✅ Да",
        "btn_no": "❌ Нет",
        "ask_stars_rate": "Сколько лайков за 1 ⭐️? (число)",
        "preview_ready": "Предпросмотр вашего челленджа 👇",
        "btn_confirm": "✅ Подтвердить и опубликовать",
        "btn_edit": "✏️ Отменить и заново",
        "challenge_published": "✅ Челлендж опубликован и закреплён!\nСсылка для регистрации:\n{link}",
        "ask_name": "Ваше имя:",
        "ask_age": "Ваш возраст?",
        "ask_city": "Ваш город?",
        "ask_photo": "Пришлите фото для баннера 📸",
        "registered": "✅ Регистрация завершена! Вы участник #{number}.",
        "must_join_first": "⚠️ Сначала вступите в канал.",
        "check_again": "✅ Я вступил, проверить снова",
        "already_liked": "Вы уже поставили лайк 😊",
        "like_added": "❤️ Лайк засчитан!",
        "about_text": "🤖 Этот бот управляет лайк-челленджами для владельцев каналов. Бесплатно ❤️",
        "creator_text": "👑 Создатель бота:\n〘Cactuc = نــوید〙\n@cactuc580"
    },
    "ar": {
        "choose_language": "اختر لغتك 🌐",
        "welcome": "مرحبًا بك في بوت تحدي الإعجابات! 🌟",
        "main_menu": "اختر أحد الخيارات:",
        "btn_new_challenge": "➕ إنشاء تحدٍ جديد",
        "btn_about": "ℹ️ عن البوت",
        "btn_creator": "👑 منشئ البوت",
        "ask_channel": "اجعل البوت مشرفًا كاملاً في قناتك أولاً، ثم أرسل رابط القناة:",
        "bot_not_admin": "❌ البوت ليس مشرفًا هناك بعد. أضفه ثم أعد إرسال الرابط.",
        "ask_winners_count": "كم عدد الفائزين النهائيين؟ (رقم)",
        "ask_prize": "🏆 جائزة المركز {rank}:",
        "ask_start_time": "متى يبدأ التحدي؟ (الصيغة: YYYY-MM-DD HH:MM)",
        "ask_end_time": "متى ينتهي؟ (نفس الصيغة)",
        "ask_stars": "تفعيل تفاعلات النجوم (⭐️)؟",
        "btn_yes": "✅ نعم",
        "btn_no": "❌ لا",
        "ask_stars_rate": "كم إعجاب لكل ⭐️؟ (رقم)",
        "preview_ready": "معاينة التحدي 👇",
        "btn_confirm": "✅ تأكيد ونشر",
        "btn_edit": "✏️ إلغاء والبدء من جديد",
        "challenge_published": "✅ تم نشر التحدي وتثبيته!\nرابط التسجيل:\n{link}",
        "ask_name": "أرسل اسمك:",
        "ask_age": "كم عمرك؟",
        "ask_city": "من أي مدينة؟",
        "ask_photo": "أرسل صورة لإضافتها لبانرك 📸",
        "registered": "✅ تم التسجيل! أنت المشارك رقم {number}.",
        "must_join_first": "⚠️ يجب الانضمام للقناة أولاً.",
        "check_again": "✅ انضممت، تحقق مرة أخرى",
        "already_liked": "لقد أعجبت بهذا مسبقًا 😊",
        "like_added": "❤️ تم تسجيل إعجابك!",
        "about_text": "🤖 هذا البوت يدير تحديات الإعجابات لأصحاب القنوات. مجاني تمامًا ❤️",
        "creator_text": "👑 منشئ البوت:\n〘Cactuc = نــوید〙\n@cactuc580"
    }
}

def t(lang, key, **kwargs):
    text = TEXTS.get(lang, TEXTS["fa"]).get(key) or TEXTS["en"].get(key, key)
    return text.format(**kwargs) if kwargs else text
