TEXTS = {
    "fa": {
        "choose_language": "🌐 زبان ربات را انتخاب کن:",
        "welcome": "🌟 خوش آمدی به ربات چالش لایکی!\n\n🎯 اینجا چالش‌ها ساخته می‌شوند و شرکت‌کننده‌ها برای جمع‌کردن لایک و ⭐️ استار رقابت می‌کنند.\n❤️ شانست رو امتحان کن و برای برنده‌شدن تلاش کن!",
        "main_menu": "👇 از منوی زیر انتخاب کن:",
        "btn_active": "🎯 چالش‌های فعال",
        "btn_new": "➕ ساخت چالش",
        "btn_stats": "📊 آمار من",
        "btn_results": "🏆 نتایج",
        "btn_settings": "⚙️ تنظیمات",
        "btn_about": "ℹ️ درباره ربات",
        "btn_creator": "👨‍💻 سازنده ربات",
        "btn_owner_manage": "🛠 مدیریت چالش‌های من",
        "btn_back": "🔙 برگشت",
        "btn_cancel": "❌ لغو",
        "btn_confirm": "✅ تأیید و ساخت",
        "btn_edit": "✏️ ویرایش / شروع دوباره",
        "btn_fa": "🇦🇫 🇮🇷 فارسی",
        "btn_en": "🇬🇧 English",
        "language_saved": "✅ زبان ذخیره شد.",
        "ask_title": "🎯 نام یا عنوان چالش را بفرست:",
        "ask_channel": "📢 لینک یا آیدی کانال را بفرست.\n\nمثال: @mychannel یا https://t.me/mychannel\n\n⚠️ ربات باید در کانال ادمین باشد.",
        "bot_not_admin": "❌ ربات در این کانال ادمین نیست یا کانال پیدا نشد. اول ربات را ادمین کن و دوباره بفرست.",
        "ask_owner_username": "👑 آیدی برگزارکننده را بفرست.\n\nمثال: @username",
        "ask_day": "📅 روز شروع چالش را انتخاب کن:",
        "today": "🟢 امروز",
        "tomorrow": "🔵 فردا",
        "day_after": "🟣 پس‌فردا",
        "choose_date": "📅 انتخاب تاریخ",
        "ask_date": "📅 تاریخ را بفرست.\n\nمی‌توانی میلادی مثل 2026-09-20 یا جلالی مثل 1405/06/29 بنویسی.",
        "bad_date": "❌ تاریخ قابل تشخیص نیست. نمونه: 2026-09-20 یا 1405/06/29",
        "ask_time": "⏰ ساعت شروع را بفرست.\n\nمثال: 10 یا 10:30 یا 18:00 یا 6 عصر",
        "bad_time": "❌ ساعت درست نیست. مثال: 10:30 یا 18:00 یا 6 عصر",
        "ask_timezone": "🌍 منطقه زمانی چالش را انتخاب کن:",
        "tz_af": "🇦🇫 افغانستان",
        "tz_ir": "🇮🇷 ایران",
        "tz_de": "🇩🇪 آلمان",
        "ask_duration": "⏳ چالش چند ساعت ادامه داشته باشد؟\n\nمثال: 24 یا 48",
        "bad_duration": "❌ مدت باید یک عدد مثبت باشد؛ مثلاً 24.",
        "ask_winners": "🏆 چند برنده نهایی داشته باشد؟",
        "bad_winners": "❌ یک عدد بین 1 تا 20 بفرست.",
        "ask_prize": "🎁 جایزه نفر {rank} را بنویس:",
        "ask_rules": "📜 قوانین چالش را بنویس.\n\nاگر قانون خاصی نداری، بنویس: پیش‌فرض",
        "ask_stars": "⭐️ آیا Stars هم در امتیاز حساب شود؟",
        "yes": "✅ بله",
        "no": "❌ خیر",
        "ask_rate": "⭐️ هر 1 Star چند لایک حساب شود؟\n\nمثال: 2",
        "bad_rate": "❌ یک عدد مثبت وارد کن؛ مثال: 2",
        "preview": "🔍 پیش‌نمایش نهایی چالش",
        "published": "🎉 چالش با موفقیت ساخته و در کانال پست شد!\n\n🔗 لینک اختصاصی ثبت‌نام:\n{link}",
        "active_empty": "🎯 فعلاً چالش فعالی وجود ندارد.",
        "active_title": "🎯 چالش‌های فعال\n\nیکی را برای مشاهده و شرکت انتخاب کن:",
        "join_challenge": "🎯 مشاهده و شرکت",
        "enter_welcome": "🌟 به چالش لایکی خوش آمدی!\n\n🎯 چالش: {title}\n🏆 {winners} جایزه منتظر برنده‌هاست!\n❤️ شانست رو آزمایش کن و برای جمع‌کردن لایک بیشتر تلاش کن.\n\nبرای ثبت‌نام چند اطلاعات کوتاه ازت می‌پرسم.",
        "ask_name": "👤 اول اسم‌ت رو بفرست:",
        "ask_age": "🎂 چند سالته؟",
        "bad_age": "❌ سن را به عدد بین 5 تا 100 بفرست.",
        "ask_city": "📍 اهل کدام شهر یا ولایت هستی؟",
        "ask_photo": "🖼️ حالا یک عکس پروفایل بفرست.\n\nبهتره همان عکسی باشد که می‌خواهی روی کارت شرکت‌کننده نمایش داده شود.",
        "already_registered": "ℹ️ تو قبلاً در این چالش ثبت‌نام کرده‌ای.\n\n👤 شماره شرکت‌کننده: {number}",
        "registered": "🎉 ثبت‌نامت با موفقیت انجام شد!\n\n👤 شرکت‌کننده شماره {number}\n📍 {city}\n\n❤️ {name}، خوش آمدی!\n🔥 تا پایان چالش سعی کن لایک‌های بیشتری جمع کنی.\n🏆 امیدوارم یکی از برنده‌ها باشی!\n\n👇 از منوی ربات هم می‌تونی امکانات دیگه رو استفاده کنی.",
        "channel_required": "⚠️ برای لایک‌کردن باید عضو کانال باشی.",
        "joined_check": "🔄 دوباره بررسی عضویت",
        "like_added": "❤️ لایک ثبت شد!",
        "already_liked": "ℹ️ تو قبلاً این پست را لایک کرده‌ای.",
        "cannot_like_self": "ℹ️ نمی‌توانی پست خودت را لایک کنی.",
        "challenge_closed": "⛔ این چالش فعال نیست.",
        "stats_pick": "📊 چند چالش فعال داری. آمار کدام چالش را می‌خواهی؟",
        "stats_none": "📊 فعلاً هیچ چالش فعالی که در آن شرکت کرده باشی وجود ندارد.",
        "stats_header": "📊 آمار تو در این چالش\n\n🎯 {title}\n📢 {channel}\n👤 شماره: {number}\n❤️ لایک: {likes}\n⭐️ Stars: {stars}\n🔥 امتیاز: {score}\n⏳ باقی‌مانده: {remaining}",
        "owner_none": "🛠 هنوز چالش فعال خودت را نداری.\n\nبرای ساخت چالش از «➕ ساخت چالش» استفاده کن.",
        "owner_pick": "🛠 چالش‌های فعال خودت:\n\nیک چالش را انتخاب کن:",
        "owner_stats": "📊 آمار چالش\n\n🎯 {title}\n📢 {channel}\n👥 ثبت‌نام کامل: {participants}\n🟢 عضو فعلی کانال: {joined}\n❤️ مجموع لایک‌ها: {likes}\n⭐️ مجموع Stars: {stars}\n🔗 ورود از لینک: {starts}\n⏳ باقی‌مانده: {remaining}",
        "report_menu": "🚨 گزارش چالش\n\nدلیل گزارش را انتخاب کن:",
        "report_prize": "🎁 جایزه پرداخت نشده",
        "report_problem": "⚠️ مشکل در اجرای چالش",
        "report_changed": "✏️ اطلاعات چالش تغییر کرده",
        "report_suspicious": "🔍 رفتار مشکوک",
        "report_other": "📝 مورد دیگر",
        "report_text": "📝 توضیح گزارش را بنویس:",
        "report_saved": "✅ گزارش شما ثبت شد.\n\n🔐 گزارش برای بررسی مدیر ارسال شد.\nممنون که به سالم ماندن چالش‌ها کمک می‌کنی.",
        "about": "🤖 این ربات برای ساخت و مدیریت چالش‌های لایکی ساخته شده است.\n\n🎯 چالش اختصاصی برای هر کانال\n❤️ لایک با بررسی عضویت\n⭐️ محاسبه Stars\n🏆 اعلام خودکار نتایج\n🚨 سیستم گزارش\n\n❤️ ساده، منظم و رایگان.",
        "creator": "👨‍💻 سازنده و طراح ربات:\n〘Cactuc = نــوید〙\n@cactuc580",
        "settings": "⚙️ تنظیمات",
        "results": "🏆 نتایج چالش‌های پایان‌یافته در آینده اینجا نمایش داده می‌شوند.",
        "cancelled": "❌ عملیات لغو شد.",
        "not_allowed": "⛔ اجازه انجام این کار را نداری.",
        "reminder": "🚨 یک ساعت تا پایان چالش!\n\n🔥 رقابت وارد آخرین مرحله شد!\n❤️ هنوز فرصت داری لایک بیشتری جمع کنی.\n⭐️ هر Star = {rate} Like\n🏆 جایزه‌ها منتظر برنده‌ها هستند!\n\n⏳ فقط 1 ساعت باقی مانده...\n🚀 تا آخر ادامه بده!",
        "ended": "🏆🎉 چالش به پایان رسید! 🎉🏆\n\n❤️ ممنون از تمام شرکت‌کننده‌ها!\n\n{winners}\n\n🎉 تبریک به برنده‌ها!\n❤️ برای همه شرکت‌کننده‌ها خسته نباشید.\n🚀 منتظر چالش‌های بعدی باشید!",
    },
    "en": {
        "choose_language": "🌐 Choose your language:",
        "welcome": "🌟 Welcome to Like Challenge Bot!\n\n🎯 Create challenges and compete for likes and ⭐️ Stars.\n❤️ Test your luck and try to win!",
        "main_menu": "👇 Choose from the menu:",
        "btn_active": "🎯 Active Challenges", "btn_new": "➕ Create Challenge", "btn_stats": "📊 My Stats", "btn_results": "🏆 Results", "btn_settings": "⚙️ Settings", "btn_about": "ℹ️ About", "btn_creator": "👨‍💻 Creator", "btn_owner_manage": "🛠 Manage My Challenges", "btn_back": "🔙 Back", "btn_cancel": "❌ Cancel", "btn_confirm": "✅ Confirm & Create", "btn_edit": "✏️ Edit / Restart", "btn_fa": "🇦🇫 🇮🇷 فارسی", "btn_en": "🇬🇧 English", "language_saved": "✅ Language saved.",
        "ask_title": "🎯 Send the challenge title:", "ask_channel": "📢 Send the channel username or link.\n\nExample: @mychannel or https://t.me/mychannel\n\n⚠️ The bot must be an admin.", "bot_not_admin": "❌ The bot is not an admin there or the channel could not be found.", "ask_owner_username": "👑 Send the organizer username.\n\nExample: @username", "ask_day": "📅 Choose the challenge start day:", "today": "🟢 Today", "tomorrow": "🔵 Tomorrow", "day_after": "🟣 Day after tomorrow", "choose_date": "📅 Choose date", "ask_date": "📅 Send a date like 2026-09-20 or 1405/06/29.", "bad_date": "❌ Date not recognized.", "ask_time": "⏰ Send start time, e.g. 10, 10:30, 18:00 or 6 pm.", "bad_time": "❌ Invalid time.", "ask_timezone": "🌍 Choose timezone:", "tz_af": "🇦🇫 Afghanistan", "tz_ir": "🇮🇷 Iran", "tz_de": "🇩🇪 Germany", "ask_duration": "⏳ How many hours should the challenge last?", "bad_duration": "❌ Duration must be a positive number.", "ask_winners": "🏆 How many final winners?", "bad_winners": "❌ Send a number from 1 to 20.", "ask_prize": "🎁 Enter the prize for rank {rank}:", "ask_rules": "📜 Send the challenge rules.\n\nIf none, type: default", "ask_stars": "⭐️ Should Stars count toward the score?", "yes": "✅ Yes", "no": "❌ No", "ask_rate": "⭐️ How many likes should 1 Star count as?", "bad_rate": "❌ Send a positive number.", "preview": "🔍 Final challenge preview", "published": "🎉 Challenge created and posted!\n\n🔗 Registration link:\n{link}", "active_empty": "🎯 There are no active challenges right now.", "active_title": "🎯 Active challenges\n\nChoose one:", "join_challenge": "🎯 View & Join", "enter_welcome": "🌟 Welcome to the Like Challenge!\n\n🎯 Challenge: {title}\n🏆 {winners} prizes are waiting!\n❤️ Test your luck and collect as many likes as possible.\n\nI’ll ask for a few quick details.", "ask_name": "👤 First, send your name:", "ask_age": "🎂 How old are you?", "bad_age": "❌ Send an age from 5 to 100.", "ask_city": "📍 Which city/province are you from?", "ask_photo": "🖼️ Now send a profile photo.", "already_registered": "ℹ️ You are already registered.\n\n👤 Participant number: {number}", "registered": "🎉 Registration successful!\n\n👤 Participant #{number}\n📍 {city}\n\n❤️ Welcome, {name}!\n🔥 Try to collect more likes until the challenge ends.\n🏆 Good luck!\n\n👇 You can also use the other bot features from the menu.", "channel_required": "⚠️ You must join the channel before liking.", "joined_check": "🔄 Check membership again", "like_added": "❤️ Like recorded!", "already_liked": "ℹ️ You already liked this post.", "cannot_like_self": "ℹ️ You cannot like your own post.", "challenge_closed": "⛔ This challenge is not active.", "stats_pick": "📊 You have several active challenges. Which one do you want?", "stats_none": "📊 You have no active challenge participation.", "stats_header": "📊 Your challenge stats\n\n🎯 {title}\n📢 {channel}\n👤 Number: {number}\n❤️ Likes: {likes}\n⭐️ Stars: {stars}\n🔥 Score: {score}\n⏳ Remaining: {remaining}", "owner_none": "🛠 You have no active challenges.\n\nUse «➕ Create Challenge»." , "owner_pick": "🛠 Your active challenges:\n\nChoose one:", "owner_stats": "📊 Challenge stats\n\n🎯 {title}\n📢 {channel}\n👥 Registrations: {participants}\n🟢 Current channel members: {joined}\n❤️ Total likes: {likes}\n⭐️ Total Stars: {stars}\n🔗 Deep-link starts: {starts}\n⏳ Remaining: {remaining}", "report_menu": "🚨 Report challenge\n\nChoose a reason:", "report_prize": "🎁 Prize not paid", "report_problem": "⚠️ Challenge problem", "report_changed": "✏️ Information changed", "report_suspicious": "🔍 Suspicious behavior", "report_other": "📝 Other", "report_text": "📝 Write the report details:", "report_saved": "✅ Your report was submitted.\n\n🔐 It was sent to the administrator for review.", "about": "🤖 A bot for creating and managing Like Challenges.\n\n🎯 Separate challenge links\n❤️ Like with membership checks\n⭐️ Star counting\n🏆 Automatic results\n🚨 Reports\n\n❤️ Simple and free.", "creator": "👨‍💻 Bot creator:\n〘Cactuc = نــوید〙\n@cactuc580", "settings": "⚙️ Settings", "results": "🏆 Results for finished challenges will appear here.", "cancelled": "❌ Operation cancelled.", "not_allowed": "⛔ You are not allowed to do this.", "reminder": "🚨 One hour left!\n\n🔥 The final stage has started!\n❤️ You can still collect more likes.\n⭐️ 1 Star = {rate} Likes\n🏆 Prizes are waiting!\n\n⏳ Only 1 hour left...\n🚀 Keep going!", "ended": "🏆🎉 Challenge ended! 🎉🏆\n\n❤️ Thanks to all participants!\n\n{winners}\n\n🎉 Congratulations to the winners!\n🚀 Stay tuned for future challenges!"
    }
}

def t(lang, key, **kwargs):
    text = TEXTS.get(lang, TEXTS["fa"]).get(key) or TEXTS["en"].get(key, key)
    return text.format(**kwargs)
